apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jh35f917g-go
  janus-idp.io/tekton: jh35f917g-go
  backstage.io/kubernetes-id: jh35f917g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jh35f917g-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
