apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jh35f917g-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jh35f917g-go 
  name: jh35f917g-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jh35f917g-go 
